### ISSUE TITLE
Handle coagulate links

### ISSUE THREAD

**Issue by LGro** [LGro/coagulate#25]
**Guides**
iOS: https://docs.flutter.dev/cookbook/navigation/set-up-universal-links
Android: https://docs.flutter.dev/cookbook/navigation/set-up-app-links

**Tasks**
- [x] wellknown file for coagulate.social
- [ ] add router to app
- [x] update xcode project as necessary including the right capabilities
- [ ] updatie the android app manifest accordingly
- [ ] host assetlinks.json on coagulate.social
- [ ] figure our how to handle the fragment, consider using https://pub.dev/packages/uni_links

**Comment by LGro** [comment]
assetlinks.json ist just missing the hash, which can be computed with
```
keytool -list -v -keystore <path-to-keystore>
```

**Comment by LGro** [comment]
plist.info is still missing the flutter deeplink key

**Comment by LGro** [comment]
Android does not seem to be handling app links at all at the moment.
